/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as AppRouteImport } from './routes/app'
import { Route as ArrayRouteImport } from './routes/array'
import { Route as AssemblyRouteImport } from './routes/assembly'
import { Route as AstroRouteImport } from './routes/astro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BioRouteImport } from './routes/bio'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as CbRouteImport } from './routes/cb'
import { Route as CbWelcomeRouteImport } from './routes/cb-welcome'
import { Route as ContentRouteImport } from './routes/content'
import { Route as DiagRouteImport } from './routes/diag'
import { Route as DopplerRouteImport } from './routes/doppler'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as FaceRouteImport } from './routes/face'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FlashRouteImport } from './routes/flash'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MapRouteImport } from './routes/map'
import { Route as NavRouteImport } from './routes/nav'
import { Route as NetchatRouteImport } from './routes/netchat'
import { Route as ObserveRouteImport } from './routes/observe'
import { Route as PcapRouteImport } from './routes/pcap'
import { Route as PermsRouteImport } from './routes/perms'
import { Route as PlayReadinessRouteImport } from './routes/play-readiness'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PttRouteImport } from './routes/ptt'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as RadiolabRouteImport } from './routes/radiolab'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WRouteImport } from './routes/w'
import { Route as WatchReportRouteImport } from './routes/watch-report'
import { Route as WcbRouteImport } from './routes/wcb'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as WxRouteImport } from './routes/wx'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ToolKeyRouteImport } from './routes/tool.$key'
import { Route as ApiContentPostsRouteImport } from './routes/api/content/posts'
import { Route as ApiContentPublishRouteImport } from './routes/api/content/publish'
import { Route as ApiPublicAstroRouteImport } from './routes/api/public/astro'
import { Route as ApiPublicCheckAccessRouteImport } from './routes/api/public/check-access'
import { Route as ApiPublicConditionsRouteImport } from './routes/api/public/conditions'
import { Route as ApiPublicFieldReportRouteImport } from './routes/api/public/field-report'
import { Route as ApiPublicForecastRouteImport } from './routes/api/public/forecast'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrayRoute = ArrayRouteImport.update({
  id: '/array',
  path: '/array',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyRoute = AssemblyRouteImport.update({
  id: '/assembly',
  path: '/assembly',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroRoute = AstroRouteImport.update({
  id: '/astro',
  path: '/astro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const CbRoute = CbRouteImport.update({
  id: '/cb',
  path: '/cb',
  getParentRoute: () => rootRouteImport,
} as any)
const CbWelcomeRoute = CbWelcomeRouteImport.update({
  id: '/cb-welcome',
  path: '/cb-welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagRoute = DiagRouteImport.update({
  id: '/diag',
  path: '/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const DopplerRoute = DopplerRouteImport.update({
  id: '/doppler',
  path: '/doppler',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceRoute = FaceRouteImport.update({
  id: '/face',
  path: '/face',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashRoute = FlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NavRoute = NavRouteImport.update({
  id: '/nav',
  path: '/nav',
  getParentRoute: () => rootRouteImport,
} as any)
const NetchatRoute = NetchatRouteImport.update({
  id: '/netchat',
  path: '/netchat',
  getParentRoute: () => rootRouteImport,
} as any)
const ObserveRoute = ObserveRouteImport.update({
  id: '/observe',
  path: '/observe',
  getParentRoute: () => rootRouteImport,
} as any)
const PcapRoute = PcapRouteImport.update({
  id: '/pcap',
  path: '/pcap',
  getParentRoute: () => rootRouteImport,
} as any)
const PermsRoute = PermsRouteImport.update({
  id: '/perms',
  path: '/perms',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayReadinessRoute = PlayReadinessRouteImport.update({
  id: '/play-readiness',
  path: '/play-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PttRoute = PttRouteImport.update({
  id: '/ptt',
  path: '/ptt',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiolabRoute = RadiolabRouteImport.update({
  id: '/radiolab',
  path: '/radiolab',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WRoute = WRouteImport.update({
  id: '/w',
  path: '/w',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchReportRoute = WatchReportRouteImport.update({
  id: '/watch-report',
  path: '/watch-report',
  getParentRoute: () => rootRouteImport,
} as any)
const WcbRoute = WcbRouteImport.update({
  id: '/wcb',
  path: '/wcb',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const WxRoute = WxRouteImport.update({
  id: '/wx',
  path: '/wx',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolKeyRoute = ToolKeyRouteImport.update({
  id: '/tool/$key',
  path: '/tool/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentPostsRoute = ApiContentPostsRouteImport.update({
  id: '/api/content/posts',
  path: '/api/content/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentPublishRoute = ApiContentPublishRouteImport.update({
  id: '/api/content/publish',
  path: '/api/content/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAstroRoute = ApiPublicAstroRouteImport.update({
  id: '/api/public/astro',
  path: '/api/public/astro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckAccessRoute = ApiPublicCheckAccessRouteImport.update({
  id: '/api/public/check-access',
  path: '/api/public/check-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConditionsRoute = ApiPublicConditionsRouteImport.update({
  id: '/api/public/conditions',
  path: '/api/public/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFieldReportRoute = ApiPublicFieldReportRouteImport.update({
  id: '/api/public/field-report',
  path: '/api/public/field-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicForecastRoute = ApiPublicForecastRouteImport.update({
  id: '/api/public/forecast',
  path: '/api/public/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agreement': typeof AgreementRoute
  '/app': typeof AppRoute
  '/array': typeof ArrayRoute
  '/assembly': typeof AssemblyRoute
  '/astro': typeof AstroRoute
  '/auth': typeof AuthRoute
  '/bio': typeof BioRoute
  '/bridge': typeof BridgeRoute
  '/briefing': typeof BriefingRoute
  '/builds': typeof BuildsRoute
  '/cb': typeof CbRoute
  '/cb-welcome': typeof CbWelcomeRoute
  '/content': typeof ContentRoute
  '/diag': typeof DiagRoute
  '/doppler': typeof DopplerRoute
  '/downloads': typeof DownloadsRoute
  '/face': typeof FaceRoute
  '/feed': typeof FeedRoute
  '/flash': typeof FlashRoute
  '/forecast': typeof ForecastRoute
  '/hardware': typeof HardwareRoute
  '/inventory': typeof InventoryRoute
  '/map': typeof MapRoute
  '/nav': typeof NavRoute
  '/netchat': typeof NetchatRoute
  '/observe': typeof ObserveRoute
  '/pcap': typeof PcapRoute
  '/perms': typeof PermsRoute
  '/play-readiness': typeof PlayReadinessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/ptt': typeof PttRoute
  '/radio': typeof RadioRoute
  '/radiolab': typeof RadiolabRoute
  '/settings': typeof SettingsRoute
  '/w': typeof WRoute
  '/watch-report': typeof WatchReportRoute
  '/wcb': typeof WcbRoute
  '/weather': typeof WeatherRoute
  '/wx': typeof WxRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/tool/$key': typeof ToolKeyRoute
  '/library/': typeof LibraryIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/content/posts': typeof ApiContentPostsRoute
  '/api/content/publish': typeof ApiContentPublishRoute
  '/api/public/astro': typeof ApiPublicAstroRoute
  '/api/public/check-access': typeof ApiPublicCheckAccessRoute
  '/api/public/conditions': typeof ApiPublicConditionsRoute
  '/api/public/field-report': typeof ApiPublicFieldReportRoute
  '/api/public/forecast': typeof ApiPublicForecastRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agreement': typeof AgreementRoute
  '/app': typeof AppRoute
  '/array': typeof ArrayRoute
  '/assembly': typeof AssemblyRoute
  '/astro': typeof AstroRoute
  '/auth': typeof AuthRoute
  '/bio': typeof BioRoute
  '/bridge': typeof BridgeRoute
  '/briefing': typeof BriefingRoute
  '/builds': typeof BuildsRoute
  '/cb': typeof CbRoute
  '/cb-welcome': typeof CbWelcomeRoute
  '/content': typeof ContentRoute
  '/diag': typeof DiagRoute
  '/doppler': typeof DopplerRoute
  '/downloads': typeof DownloadsRoute
  '/face': typeof FaceRoute
  '/feed': typeof FeedRoute
  '/flash': typeof FlashRoute
  '/forecast': typeof ForecastRoute
  '/hardware': typeof HardwareRoute
  '/inventory': typeof InventoryRoute
  '/map': typeof MapRoute
  '/nav': typeof NavRoute
  '/netchat': typeof NetchatRoute
  '/observe': typeof ObserveRoute
  '/pcap': typeof PcapRoute
  '/perms': typeof PermsRoute
  '/play-readiness': typeof PlayReadinessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/ptt': typeof PttRoute
  '/radio': typeof RadioRoute
  '/radiolab': typeof RadiolabRoute
  '/settings': typeof SettingsRoute
  '/w': typeof WRoute
  '/watch-report': typeof WatchReportRoute
  '/wcb': typeof WcbRoute
  '/weather': typeof WeatherRoute
  '/wx': typeof WxRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/tool/$key': typeof ToolKeyRoute
  '/library': typeof LibraryIndexRoute
  '/store': typeof StoreIndexRoute
  '/api/content/posts': typeof ApiContentPostsRoute
  '/api/content/publish': typeof ApiContentPublishRoute
  '/api/public/astro': typeof ApiPublicAstroRoute
  '/api/public/check-access': typeof ApiPublicCheckAccessRoute
  '/api/public/conditions': typeof ApiPublicConditionsRoute
  '/api/public/field-report': typeof ApiPublicFieldReportRoute
  '/api/public/forecast': typeof ApiPublicForecastRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agreement': typeof AgreementRoute
  '/app': typeof AppRoute
  '/array': typeof ArrayRoute
  '/assembly': typeof AssemblyRoute
  '/astro': typeof AstroRoute
  '/auth': typeof AuthRoute
  '/bio': typeof BioRoute
  '/bridge': typeof BridgeRoute
  '/briefing': typeof BriefingRoute
  '/builds': typeof BuildsRoute
  '/cb': typeof CbRoute
  '/cb-welcome': typeof CbWelcomeRoute
  '/content': typeof ContentRoute
  '/diag': typeof DiagRoute
  '/doppler': typeof DopplerRoute
  '/downloads': typeof DownloadsRoute
  '/face': typeof FaceRoute
  '/feed': typeof FeedRoute
  '/flash': typeof FlashRoute
  '/forecast': typeof ForecastRoute
  '/hardware': typeof HardwareRoute
  '/inventory': typeof InventoryRoute
  '/map': typeof MapRoute
  '/nav': typeof NavRoute
  '/netchat': typeof NetchatRoute
  '/observe': typeof ObserveRoute
  '/pcap': typeof PcapRoute
  '/perms': typeof PermsRoute
  '/play-readiness': typeof PlayReadinessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/ptt': typeof PttRoute
  '/radio': typeof RadioRoute
  '/radiolab': typeof RadiolabRoute
  '/settings': typeof SettingsRoute
  '/w': typeof WRoute
  '/watch-report': typeof WatchReportRoute
  '/wcb': typeof WcbRoute
  '/weather': typeof WeatherRoute
  '/wx': typeof WxRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/tool/$key': typeof ToolKeyRoute
  '/library/': typeof LibraryIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/content/posts': typeof ApiContentPostsRoute
  '/api/content/publish': typeof ApiContentPublishRoute
  '/api/public/astro': typeof ApiPublicAstroRoute
  '/api/public/check-access': typeof ApiPublicCheckAccessRoute
  '/api/public/conditions': typeof ApiPublicConditionsRoute
  '/api/public/field-report': typeof ApiPublicFieldReportRoute
  '/api/public/forecast': typeof ApiPublicForecastRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/agreement'
    | '/app'
    | '/array'
    | '/assembly'
    | '/astro'
    | '/auth'
    | '/bio'
    | '/bridge'
    | '/briefing'
    | '/builds'
    | '/cb'
    | '/cb-welcome'
    | '/content'
    | '/diag'
    | '/doppler'
    | '/downloads'
    | '/face'
    | '/feed'
    | '/flash'
    | '/forecast'
    | '/hardware'
    | '/inventory'
    | '/map'
    | '/nav'
    | '/netchat'
    | '/observe'
    | '/pcap'
    | '/perms'
    | '/play-readiness'
    | '/pricing'
    | '/privacy'
    | '/ptt'
    | '/radio'
    | '/radiolab'
    | '/settings'
    | '/w'
    | '/watch-report'
    | '/wcb'
    | '/weather'
    | '/wx'
    | '/checkout/return'
    | '/library/$slug'
    | '/store/$slug'
    | '/tool/$key'
    | '/library/'
    | '/store/'
    | '/api/content/posts'
    | '/api/content/publish'
    | '/api/public/astro'
    | '/api/public/check-access'
    | '/api/public/conditions'
    | '/api/public/field-report'
    | '/api/public/forecast'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/agreement'
    | '/app'
    | '/array'
    | '/assembly'
    | '/astro'
    | '/auth'
    | '/bio'
    | '/bridge'
    | '/briefing'
    | '/builds'
    | '/cb'
    | '/cb-welcome'
    | '/content'
    | '/diag'
    | '/doppler'
    | '/downloads'
    | '/face'
    | '/feed'
    | '/flash'
    | '/forecast'
    | '/hardware'
    | '/inventory'
    | '/map'
    | '/nav'
    | '/netchat'
    | '/observe'
    | '/pcap'
    | '/perms'
    | '/play-readiness'
    | '/pricing'
    | '/privacy'
    | '/ptt'
    | '/radio'
    | '/radiolab'
    | '/settings'
    | '/w'
    | '/watch-report'
    | '/wcb'
    | '/weather'
    | '/wx'
    | '/checkout/return'
    | '/library/$slug'
    | '/store/$slug'
    | '/tool/$key'
    | '/library'
    | '/store'
    | '/api/content/posts'
    | '/api/content/publish'
    | '/api/public/astro'
    | '/api/public/check-access'
    | '/api/public/conditions'
    | '/api/public/field-report'
    | '/api/public/forecast'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/agreement'
    | '/app'
    | '/array'
    | '/assembly'
    | '/astro'
    | '/auth'
    | '/bio'
    | '/bridge'
    | '/briefing'
    | '/builds'
    | '/cb'
    | '/cb-welcome'
    | '/content'
    | '/diag'
    | '/doppler'
    | '/downloads'
    | '/face'
    | '/feed'
    | '/flash'
    | '/forecast'
    | '/hardware'
    | '/inventory'
    | '/map'
    | '/nav'
    | '/netchat'
    | '/observe'
    | '/pcap'
    | '/perms'
    | '/play-readiness'
    | '/pricing'
    | '/privacy'
    | '/ptt'
    | '/radio'
    | '/radiolab'
    | '/settings'
    | '/w'
    | '/watch-report'
    | '/wcb'
    | '/weather'
    | '/wx'
    | '/checkout/return'
    | '/library/$slug'
    | '/store/$slug'
    | '/tool/$key'
    | '/library/'
    | '/store/'
    | '/api/content/posts'
    | '/api/content/publish'
    | '/api/public/astro'
    | '/api/public/check-access'
    | '/api/public/conditions'
    | '/api/public/field-report'
    | '/api/public/forecast'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AgreementRoute: typeof AgreementRoute
  AppRoute: typeof AppRoute
  ArrayRoute: typeof ArrayRoute
  AssemblyRoute: typeof AssemblyRoute
  AstroRoute: typeof AstroRoute
  AuthRoute: typeof AuthRoute
  BioRoute: typeof BioRoute
  BridgeRoute: typeof BridgeRoute
  BriefingRoute: typeof BriefingRoute
  BuildsRoute: typeof BuildsRoute
  CbRoute: typeof CbRoute
  CbWelcomeRoute: typeof CbWelcomeRoute
  ContentRoute: typeof ContentRoute
  DiagRoute: typeof DiagRoute
  DopplerRoute: typeof DopplerRoute
  DownloadsRoute: typeof DownloadsRoute
  FaceRoute: typeof FaceRoute
  FeedRoute: typeof FeedRoute
  FlashRoute: typeof FlashRoute
  ForecastRoute: typeof ForecastRoute
  HardwareRoute: typeof HardwareRoute
  InventoryRoute: typeof InventoryRoute
  MapRoute: typeof MapRoute
  NavRoute: typeof NavRoute
  NetchatRoute: typeof NetchatRoute
  ObserveRoute: typeof ObserveRoute
  PcapRoute: typeof PcapRoute
  PermsRoute: typeof PermsRoute
  PlayReadinessRoute: typeof PlayReadinessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PttRoute: typeof PttRoute
  RadioRoute: typeof RadioRoute
  RadiolabRoute: typeof RadiolabRoute
  SettingsRoute: typeof SettingsRoute
  WRoute: typeof WRoute
  WatchReportRoute: typeof WatchReportRoute
  WcbRoute: typeof WcbRoute
  WeatherRoute: typeof WeatherRoute
  WxRoute: typeof WxRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
  ToolKeyRoute: typeof ToolKeyRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  ApiContentPostsRoute: typeof ApiContentPostsRoute
  ApiContentPublishRoute: typeof ApiContentPublishRoute
  ApiPublicAstroRoute: typeof ApiPublicAstroRoute
  ApiPublicCheckAccessRoute: typeof ApiPublicCheckAccessRoute
  ApiPublicConditionsRoute: typeof ApiPublicConditionsRoute
  ApiPublicFieldReportRoute: typeof ApiPublicFieldReportRoute
  ApiPublicForecastRoute: typeof ApiPublicForecastRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/array': {
      id: '/array'
      path: '/array'
      fullPath: '/array'
      preLoaderRoute: typeof ArrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly': {
      id: '/assembly'
      path: '/assembly'
      fullPath: '/assembly'
      preLoaderRoute: typeof AssemblyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astro': {
      id: '/astro'
      path: '/astro'
      fullPath: '/astro'
      preLoaderRoute: typeof AstroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cb': {
      id: '/cb'
      path: '/cb'
      fullPath: '/cb'
      preLoaderRoute: typeof CbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cb-welcome': {
      id: '/cb-welcome'
      path: '/cb-welcome'
      fullPath: '/cb-welcome'
      preLoaderRoute: typeof CbWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diag': {
      id: '/diag'
      path: '/diag'
      fullPath: '/diag'
      preLoaderRoute: typeof DiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doppler': {
      id: '/doppler'
      path: '/doppler'
      fullPath: '/doppler'
      preLoaderRoute: typeof DopplerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face': {
      id: '/face'
      path: '/face'
      fullPath: '/face'
      preLoaderRoute: typeof FaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash': {
      id: '/flash'
      path: '/flash'
      fullPath: '/flash'
      preLoaderRoute: typeof FlashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nav': {
      id: '/nav'
      path: '/nav'
      fullPath: '/nav'
      preLoaderRoute: typeof NavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netchat': {
      id: '/netchat'
      path: '/netchat'
      fullPath: '/netchat'
      preLoaderRoute: typeof NetchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observe': {
      id: '/observe'
      path: '/observe'
      fullPath: '/observe'
      preLoaderRoute: typeof ObserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcap': {
      id: '/pcap'
      path: '/pcap'
      fullPath: '/pcap'
      preLoaderRoute: typeof PcapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perms': {
      id: '/perms'
      path: '/perms'
      fullPath: '/perms'
      preLoaderRoute: typeof PermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-readiness': {
      id: '/play-readiness'
      path: '/play-readiness'
      fullPath: '/play-readiness'
      preLoaderRoute: typeof PlayReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptt': {
      id: '/ptt'
      path: '/ptt'
      fullPath: '/ptt'
      preLoaderRoute: typeof PttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radiolab': {
      id: '/radiolab'
      path: '/radiolab'
      fullPath: '/radiolab'
      preLoaderRoute: typeof RadiolabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-report': {
      id: '/watch-report'
      path: '/watch-report'
      fullPath: '/watch-report'
      preLoaderRoute: typeof WatchReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wcb': {
      id: '/wcb'
      path: '/wcb'
      fullPath: '/wcb'
      preLoaderRoute: typeof WcbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wx': {
      id: '/wx'
      path: '/wx'
      fullPath: '/wx'
      preLoaderRoute: typeof WxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$key': {
      id: '/tool/$key'
      path: '/tool/$key'
      fullPath: '/tool/$key'
      preLoaderRoute: typeof ToolKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/posts': {
      id: '/api/content/posts'
      path: '/api/content/posts'
      fullPath: '/api/content/posts'
      preLoaderRoute: typeof ApiContentPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/publish': {
      id: '/api/content/publish'
      path: '/api/content/publish'
      fullPath: '/api/content/publish'
      preLoaderRoute: typeof ApiContentPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/astro': {
      id: '/api/public/astro'
      path: '/api/public/astro'
      fullPath: '/api/public/astro'
      preLoaderRoute: typeof ApiPublicAstroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-access': {
      id: '/api/public/check-access'
      path: '/api/public/check-access'
      fullPath: '/api/public/check-access'
      preLoaderRoute: typeof ApiPublicCheckAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conditions': {
      id: '/api/public/conditions'
      path: '/api/public/conditions'
      fullPath: '/api/public/conditions'
      preLoaderRoute: typeof ApiPublicConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/field-report': {
      id: '/api/public/field-report'
      path: '/api/public/field-report'
      fullPath: '/api/public/field-report'
      preLoaderRoute: typeof ApiPublicFieldReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forecast': {
      id: '/api/public/forecast'
      path: '/api/public/forecast'
      fullPath: '/api/public/forecast'
      preLoaderRoute: typeof ApiPublicForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AgreementRoute: AgreementRoute,
  AppRoute: AppRoute,
  ArrayRoute: ArrayRoute,
  AssemblyRoute: AssemblyRoute,
  AstroRoute: AstroRoute,
  AuthRoute: AuthRoute,
  BioRoute: BioRoute,
  BridgeRoute: BridgeRoute,
  BriefingRoute: BriefingRoute,
  BuildsRoute: BuildsRoute,
  CbRoute: CbRoute,
  CbWelcomeRoute: CbWelcomeRoute,
  ContentRoute: ContentRoute,
  DiagRoute: DiagRoute,
  DopplerRoute: DopplerRoute,
  DownloadsRoute: DownloadsRoute,
  FaceRoute: FaceRoute,
  FeedRoute: FeedRoute,
  FlashRoute: FlashRoute,
  ForecastRoute: ForecastRoute,
  HardwareRoute: HardwareRoute,
  InventoryRoute: InventoryRoute,
  MapRoute: MapRoute,
  NavRoute: NavRoute,
  NetchatRoute: NetchatRoute,
  ObserveRoute: ObserveRoute,
  PcapRoute: PcapRoute,
  PermsRoute: PermsRoute,
  PlayReadinessRoute: PlayReadinessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PttRoute: PttRoute,
  RadioRoute: RadioRoute,
  RadiolabRoute: RadiolabRoute,
  SettingsRoute: SettingsRoute,
  WRoute: WRoute,
  WatchReportRoute: WatchReportRoute,
  WcbRoute: WcbRoute,
  WeatherRoute: WeatherRoute,
  WxRoute: WxRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  StoreSlugRoute: StoreSlugRoute,
  ToolKeyRoute: ToolKeyRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  ApiContentPostsRoute: ApiContentPostsRoute,
  ApiContentPublishRoute: ApiContentPublishRoute,
  ApiPublicAstroRoute: ApiPublicAstroRoute,
  ApiPublicCheckAccessRoute: ApiPublicCheckAccessRoute,
  ApiPublicConditionsRoute: ApiPublicConditionsRoute,
  ApiPublicFieldReportRoute: ApiPublicFieldReportRoute,
  ApiPublicForecastRoute: ApiPublicForecastRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
